# the language the plugin and bot should run in
# check the Spigot page for supported languages.
#   you can add your own language files inside the language
#   folder and put the name of the file (without the .yml part) here.
language: "en_US"

botInfo:
  # the prefix the bot should listen to (can be any length)
  prefix: "-"
  # token - you should keep this a secret
  # get one from the Discord developer portal
  token: ""
  # the bot will listen for commands from regular users on these chats
  # it will always reply to commands from who has the roles in adminCommandRoles
  channelsToListen:
    - "000000000000000000" # general
  # server where the bot will look for roles
  server: "000000000000000000"

database:
  # which database to use. Options are sqlite (file) or mysql
  # for mysql you need to set the mysql configs below
  type: "sqlite"
  # prefix for the tables that will be created in the databases
  # (do not include the _)
  tablePrefix: "syncbot"
  # info for connecting to the MySQL database, ignored unless
  # database.type is "mysql"
  mysql:
    dbhost: ""
    dbport: 3306
    dbname: ""
    dbuser: ""
    dbpass: ""

# if the bot should require users to be verified
# to verify, users should type /drs verify in the chat
# if DRS whitelist is enabled, they will be given the code when they try to join
requireVerification: false

# the URL of an invite for your Discord server (will be sent to unlinked users when
# they try to verify their account)
discordUrl: ""

# whether or not to delete the user commands after
# reacting and a few seconds pass
deleteCommands: false

# time, in seconds, to wait before deleting a command
# this is ignored if deleteCommands is false, but is necessary
deleteAfter: 10

# how the bot should change the Discord nicknames when the user is linked
# possible values are:
# - no: the bot will not touch the Discord nicknames
# - after: the bot will put the Minecraft user in parenthesis: discord name (mc user)
# - replace: the bot will replace the user's Discord nickname with the Minecraft user
# IF YOU SET THIS TO ANYTHING OTHER THAN "no" YOU NEED TO GIVE THE BOT A DISCORD ROLE
# HIGHER THAN ANY OTHER ROLES. Nickname editing will also not work with server owners :(
changeNicknames: "no"

# should the bot manage a whitelist?
# it will kick those that don't have the whitelist role if enabled.
# please disable the default whitelist with /whitelist off if you are using this.
manageWhitelist: false

# IDs of the roles that should have their members in the whitelist.json file
whitelistRoles:
  - "000000000000000000" # whitelisted

# if the bot should give the linked players a role (which will be removed if they are unlinked)
giveLinkedRole: false

# the role that should be given to linked users. Ignored if giveLinkedRole is false
linkedRole: "000000000000000000" # linked

# IDs of the roles that should be allowed to use admin commands such as unlink and info
adminCommandRoles:
  - "000000000000000000" # administrator
  - "000000000000000000" # moderator

# permission groups to add to users with one of the roles in the list
# follow the example and remove or add more as needed
groups:
  admin:
    - "000000000000000000" # administrator
  mod:
    - "000000000000000000" # moderator
  vip:
    - "000000000000000000" # twitch subs
    - "000000000000000000" # irl friends or something

# emojis to use for reaction
# to use a custom emoji, you can put its ID instead of the actual
# unicode emoji
react:
  # if the command was successful
  onSuccess: "✅"
  # if the user made an error (account already linked, Minecraft user does not exist, etc.)
  onUserError: "❌"
  # if something went wrong with the bot (this should never happen. If it does, either something is wrong
  # with the config or the bot. If you need help, contact the developer).
  onBotError: "⚠"
  # if the user does not have permission for that command
  onPermissionError: "🛑"

# other server to use instead of Mojang API
# leave blank to use default Mojang one
alternativeServer: ""