name: RoleSync
version: 1.0.0-BETA.4
author: Nicho
description: Plugin to synchronize LuckPerms permissions with Discord roles and manage the whitelist with a Discord role if wanted.
main: dev.nicho.rolesync.RoleSync
softdepend:
  - LuckPerms
loadbefore: # Minecord uses an older API version. The methods from their version have been deprecated but not removed.
  - Minecord
commands:
  discordrolesync:
    description: Commands to manage the DiscordRoleSync plugin.
    aliases:
      - drs
