name: RoleSync
version: 1.0.0-BETA
author: Nicho
description: Plugin to synchronize LuckPerms permissions with Discord roles and manage the whitelist with a Discord role if wanted.
main: dev.nicho.rolesync.RoleSync
loadbefore:
  - LuckPerms
  - someplugin